services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - vendor_data:/var/www/vendor
    environment:
      - APP_ENV=dev
    depends_on:
      - db
    networks:
      - network_docker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend
    networks:
      - network_docker

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"
    networks:
      - network_docker
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - network_docker

volumes:
  vendor_data:

networks:
  network_docker:
    driver: bridge